name: Deploy Laravel Application to Production Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.1.0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2.8 

    - name: Install Composer Dependencies
      run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'

    - name: Install NPM Dependencies
      run: npm install

    - name: Build NPM Assets
      run: npm run build

    - name: Synchronize Files To Server
      uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DOC_SUPPORT_PKEY }}
        SOURCE: "docsupport/"
        REMOTE_HOST: ${{ secrets.DOC_SUPPORT_IP }}
        REMOTE_USER: ${{ secrets.DOC_SUPPORT_USER }}
        TARGET: "/var/www/html/docsupport.gabrieligbinosa.com"

    - name: Run Remote/Artisan Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DOC_SUPPORT_IP }}
        username: ${{ secrets.DOC_SUPPORT_USER }}
        key: ${{ secrets.DOC_SUPPORT_PKEY}}
        script: |
          cd /var/www/html/docsupport.gabrieligbinosa.com
          php artisan migrate --force

          php artisan optimize:clear
  
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache